# Generated by Django 4.2.4 on 2023-08-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat', models.IntegerField(verbose_name='PAT N°')),
                ('munic', models.CharField(max_length=50, verbose_name='Município')),
                ('uf', models.CharField(max_length=2)),
                ('datini', models.DateField()),
                ('datfin', models.DateField()),
                ('datdivat', models.DateField()),
                ('valtrib', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valmul', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valcred', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valatu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('datvalatu', models.DateField()),
                ('datand', models.DateField()),
                ('anda', models.IntegerField()),
                ('datprazo', models.DateField()),
            ],
        ),
    ]
