# Generated by Django 4.2.4 on 2023-08-16 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeFederativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('uf', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('pat', models.IntegerField(verbose_name='PAT N°')),
                ('munic', models.CharField(max_length=50, verbose_name='Município')),
                ('datini', models.DateField(verbose_name='Data Inicial')),
                ('datfin', models.DateField(verbose_name='Data Final')),
                ('datdivat', models.DateField(verbose_name='Data Dívida Ativa')),
                ('valtrib', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor do Atributo')),
                ('valmul', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor da Multa')),
                ('valcred', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor do Crédito')),
                ('valatu', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor do Atualizado')),
                ('datvalatu', models.DateField(verbose_name='Data Valor Atualizado')),
                ('datand', models.DateField(verbose_name='Data Andamento')),
                ('anda', models.IntegerField(verbose_name='Andamento Atual')),
                ('datprazo', models.DateField(verbose_name='Data Prazo')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidadefederativa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
