# Generated by Django 4.2.4 on 2023-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamento',
            name='arq3',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Arquivo'),
        ),
    ]
