# Generated by Django 4.2.4 on 2023-08-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadministrativo',
            name='pat',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Processo N°'),
        ),
    ]
