# Generated by Django 4.2.4 on 2023-08-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campo',
            old_name='nome',
            new_name='nomeuf',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='descricao',
        ),
    ]
