# Generated by Django 4.2.4 on 2023-08-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadministrativo',
            name='pat',
            field=models.IntegerField(help_text='Número real do processo.', unique=True, verbose_name='PAT N°'),
        ),
    ]
