# Generated by Django 4.2.4 on 2023-08-16 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_rename_nome_campo_nomeuf_remove_campo_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('pat', models.IntegerField()),
                ('munic', models.CharField(max_length=50, verbose_name='Município')),
                ('datini', models.DateField()),
                ('datfin', models.DateField()),
                ('datdivat', models.DateField()),
                ('valtrib', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valmul', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valcred', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valatu', models.DecimalField(decimal_places=2, max_digits=9)),
                ('datvalatu', models.DateField()),
                ('datand', models.DateField()),
                ('anda', models.IntegerField()),
                ('datprazo', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeFederativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('uf', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Campo',
        ),
        migrations.AddField(
            model_name='processoadministrativo',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidadefederativa'),
        ),
    ]
