# Generated by Django 4.2.4 on 2023-09-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_processoadministrativo_valtrib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadministrativo',
            name='valtrib',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
