# Generated by Django 4.2.4 on 2023-08-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_andamento_criador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andamento',
            name='criador',
        ),
    ]
