# Generated by Django 4.2.4 on 2023-09-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_andamento_criador_processoadministrativo_criador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andamento',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='processoadministrativo',
            name='criador',
        ),
    ]
