# Generated by Django 4.2.4 on 2023-08-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_processoadministrativo_datini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadministrativo',
            name='datfin',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final'),
        ),
    ]
