# Generated by Django 4.2.4 on 2023-09-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_processoadministrativo_valtrib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadministrativo',
            name='pat',
            field=models.CharField(max_length=10, unique=True, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='valatu',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='valcred',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='valmul',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
