# Generated by Django 4.2.4 on 2023-09-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_andamento_criador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamento',
            name='andamento',
            field=models.CharField(choices=[('abertura', 'Abertura'), ('parecerfiscal', 'Parecer Fiscal'), ('decisao1instancia', 'Decisão 1ª Instância'), ('suspensoparafiscalizacaofutura', 'Suspenso Para Fiscalização Futura'), ('autodeinfracaoetermodeintimacao-aiti.', 'Auto de Infração e Termo de Intimação - AITI.'), ('termodeintimacaofiscal-tif.', 'Termo de Intimação Fiscal - TIF.'), ('decisaode2instancia', 'Decisão de 2ª Instância'), ('cobrancadedocumentacao', 'Cobrança de Documentação'), ('recusovoluntario', 'Recurso Voluntário'), ('fimdocontratocomaassessoria', 'Fim do Contrato com a Assessoria'), ('manifestacao', 'Manifestação'), ('recebimentodoar', 'Recebimento do AR'), ('despacho', 'Despacho'), ('aguardandopagamento', 'Aguardando Pagamento'), ('apresentacaodedocumentacaoparaanalise', 'Apresentação de Documentação para Análise'), ('aguardandoar', 'Aguardando AR'), ('oficio', 'Ofício'), ('revelia', 'Revelia'), ('execucao', 'Execução'), ('confissaodedividaparcelamento', 'Confissão de Dívida (Parcelamento)'), ('reenviodedocumento', 'Reenvio de Documento'), ('parecerjuridico', 'Parecer Juridico'), ('certidao', 'Certidão'), ('encaminhado', 'Encaminhado')], max_length=100, verbose_name='Andamento'),
        ),
        migrations.AlterField(
            model_name='andamento',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='andamento',
            name='dataprazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='andamento',
            name='datrecebimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='andamento',
            name='dias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='andamento',
            name='funcionario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='andamento',
            name='locprocesso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
