# Generated by Django 4.2.4 on 2023-08-15 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_delete_unidadefederativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoadministrativo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='processoadministrativo',
            name='criados',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processoadministrativo',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='anda',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='datand',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='datdivat',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='datfin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='datini',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='datprazo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='datvalatu',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='pat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='valatu',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='valcred',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='valmul',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='valtrib',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
