# Generated by Django 4.2.4 on 2023-08-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_processoadministrativo_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosProcAdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('arq1', models.FileField(upload_to='uploads/', verbose_name='Arquivo 1')),
                ('arq2', models.FileField(upload_to='uploads/', verbose_name='Arquivo 2')),
                ('arq3', models.FileField(upload_to='uploads/', verbose_name='Arquivo 3')),
                ('arq4', models.FileField(upload_to='uploads/', verbose_name='Arquivo 4')),
                ('arq5', models.FileField(upload_to='uploads/', verbose_name='Arquivo 5')),
                ('arq6', models.FileField(upload_to='uploads/', verbose_name='Arquivo 6')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
