# Generated by Django 4.2.4 on 2023-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_processoadministrativo_datfin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadministrativo',
            name='datand',
            field=models.DateField(blank=True, null=True, verbose_name='Data Andamento'),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='datdivat',
            field=models.DateField(blank=True, null=True, verbose_name='Data Dívida Ativa'),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='datprazo',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prazo'),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='datvalatu',
            field=models.DateField(blank=True, null=True, verbose_name='Data Valor Atualizado'),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='valatu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor do Atualizado'),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='valcred',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor do Crédito'),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='valmul',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor da Multa'),
        ),
        migrations.AlterField(
            model_name='processoadministrativo',
            name='valtrib',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor do Atributo'),
        ),
    ]
